.TH "WIMENU" 1 "Oct, 2009" "wmii-@VERSION@"

.SH NAME
.P
wimenu \- The wmii menu program

.SH SYNOPSIS
.P
wimenu \fI[\-a \fI<address>\fR]\fR \fI[\-c]\fR \fI[\-h \fI<history file>\fR]\fR \fI[\-i]\fR \fI[\-K]\fR \fI[\-k \fI<keys file>\fR]\fR \fI[\-n \fI<history count>\fR]\fR \fI[\-p \fI<prompt>\fR]\fR \fI[\-s \fI<screen>\fR]\fR 
.P
wimenu \-v

.SH DESCRIPTION
.P
\fBwimenu\fR is \fBwmii\fR's standard menu program. It's used
extensively by \fBwmii\fR and related programs to prompt the user
for input. The standard configuration uses it to launch
programs, select views, and perform standard actions. It
supports basic item completion and history support.

.SH ARGUMENTS
.TP
\-a

.RS
The address at which to connect to \fBwmii\fR.
.RE
.TP
\-c

.RS
Prints the contents of the input buffer each time the
user inputs a character, as such:
.RE

.RS
.RS
\fI<text before caret>\fR\e0\fI<text after caret>\fR\e0
.RE
.RE
.TP
\-h \fI<history file>\fR

.RS
Causes \fBwimenu\fR to read its command history from
\fI<history file>\fR and to append its result to that file if
\fI\-n\fR is given.
.RE
.TP
\-i

.RS
Causes matching of completion items to be performed in a
case insensitive manner.
.RE
.TP
\-K

.RS
Prevents \fBwimenu\fR from initializing its default key
bindings. WARNING: If you do this, be sure to bind a key
with the Accept or Reject action, of you won't be able
to exit \fBwimenu\fR.
.RE
.TP
\-k \fI<key file>\fR

.RS
Key bindings will be read from \fI<key file>\fR. Bindings
appear as:
.RE

.RS
.RS
\fI<key>\fR \fI[action]\fR \fI[args]\fR
.RE
.RE

.RS
where \fI<key>\fR is a key name, similar to the format used by
wmii. For action and args, please refer to the default
bindings, provided in the source distribution under
cmd/menu/keys.txt, or use strings(1) on the \fBwimenu\fR
executable (this level of customization is discouraged,
and reserved for the determined).
.RE
.TP
\-n \fI<count>\fR

.RS
Write at most \fI<count>\fR items back to the history file.
The file is never modified unless this option is
provided. Duplicates are filtered out within a 20 item
sliding window before this limit is imposed.
.RE
.TP
\-p \fI<prompt>\fR

.RS
The string \fI<prompt>\fR will be show before the input field
when the menu is opened.
.RE
.TP
\-s \fI<screen>\fR

.RS
Suggests that the menu open on Xinerama screen \fI<screen>\fR
.RE

.SH ENVIRONMENT
.TP
WMII_ADDRESS
Socket file of Used by wmiir(1).
.TP
NAMESPACE

.RS
The namespace directory to use if no address is
provided.
.RE
.SH SEE ALSO
.P
dmenu(1), wmiir(1)

.P
\fI[1]\fR http://www.suckless.org/wiki/wmii/tips/9p_tips


.\" man code generated by txt2tags 2.5 (http://txt2tags.sf.net)
.\" cmdline: txt2tags -o- wimenu.man1

