.TH WMIIWM 1 wmii-VERSION
.SH NAME
wmiiwm \(em window manager improved\(emimproved (core)
.SH SYNOPSIS
.B wmiiwm
.B \-a
.I <address>
.RB [ \-c ]
.RB [ \-v ]
.SH DESCRIPTION

.SS Options
.TP
.BI \-a " address"
Lets you specify the address which
.B wmiiwm
uses to listen for connections.  The syntax for
.I address
is taken (along with many other profound ideas) from the Plan 9 operating
system and has the form
.B unix!/path/to/socket 
for unix socket files, and
.B tcp!hostname!port
for tcp sockets.
.TP
.B \-c
Checks if another window manager is running. If not it exits with termination code
0.
.TP
.B \-v
Prints version information to stdout, then exits.
.BR wmiir (1).
.SH SEE ALSO
.BR wmii (1),
.BR dmenu (1),
.BR wmiir (1)
