.TH WMIIR 1 wmii\-VERSION
.SH NAME
wmiiloop \(em wmii event loop processor
.SH SYNOPSIS
.B cat 
.I events
| 
.B wmiiloop
|
.B sh
.br
.SH DESCRIPTION
.SS Overview
.B wmiiloop
is an awk script which preprocesses
.BR sh (1)
syntax to simplify writing a wmii event loop.

.br
.B eventloop
associates lines begining with 
.IR Event ", " Action ", or " Key
(henceforth known as
.BR $keyword ),
followed by arbitrary text (henceforth known as
.BR $args ),
with functions which call any indented lines which follow.
In the function names, all non-alphanumeric characters in $args
are replaced with underscores (_). The functions are named
$keyword'_'$args.

Any variables in the unintented lines are interpolated by the shell.

Additionally, each declaration's
.B $args
are assigned to a variable named
.BR $keyword's' .
In this case, no transliteration occurs. For instance, the following
declaration:

.B Key 
.IB $MODKEY -j
.br
	echo Got $@

yields (assuming 
.I $MODKEY
is set to 
.IR Mod1 ):

Keys=" $Keys Mod1-j"
.br
Mod1_j() {
.br
	echo Got $@
.br
}

.SH SEE ALSO
.BR wmii (1),
.BR wmiir (1),
.B PREFIX/etc/wmiirc

