.TH "wmiir" 1 "Oct, 2009" "wmii-@VERSION@"

.SH NAME
.P
wmiir \- The wmii 9P filesystem client

.SH SYNOPSIS
.P
wmiir \fI[\-a \fI<address>\fR]\fR {create | ls \fI[\-dlp]\fR | read | remove | write} \fI<file>\fR 
.P
wmiir \fI[\-a \fI<address>\fR]\fR xwrite \fI<file>\fR \fI<data>\fR ... 
.P
wmiir \-v

.SH DESCRIPTION
.P
\fBwmiir\fR is a simple 9P filesystem client which ships with \fBwmii\fR, and connects
to its virtual filesystem by default. \fBwmiir\fR is most often used to query and
issue commands to \fBwmii\fR, both from the command line and from its \fBsh\fR\-based
configuration scripts.

.SH ARGUMENTS
.TP
\-a
The address at which to connect to \fBwmii\fR.

.SH COMMANDS
.TP
create \fI<file>\fR
Creates a new file or directory in the filesystem. Permissions and
file type are inferred by \fBwmii\fR. The contents of the standard input
are written to the new file.
.TP
ls \fI[\-dlp]\fR \fI<path>\fR
Lists the contents of \fI<path>\fR.

Flags:
.RS 8
.TP
\-d
Don't list the contents of directories.
.TP
\-l
Long output. For each file, list its permissions, owner,
group, size (bytes), mtime, and name.
.TP
\-p
Print the full path to each file.
.RS -8
.TP
read \fI<file>\fR
Reads the entire contents of a file from the filesystem. Blocks until
interrupted or EOF is received.

Synonyms: \fBcat\fR
.TP
remove \fI<path>\fR
Removes \fI<path>\fR from the filesystem.

Synonyms: rm
.TP
write \fI<file>\fR
Writes the contents of the standard input to \fI<file>\fR.
.TP
xwrite \fI<file>\fR \fI<data>\fR ...
Writes each argument after \fI<file>\fR to the latter.


.SH ENVIRONMENT
.TP
\fB$WMII_ADDRESS\fR
The address at which to connect to wmii.
.TP
\fB$NAMESPACE\fR
The namespace directory to use if no address is
provided.


.SH SEE ALSO
.P
wmii(1), libixp\fI[2]\fR

.P
\fI[1]\fR http://www.suckless.org/wiki/wmii/tips/9p_tips 
.P
\fI[2]\fR http://libs.suckless.org/libixp


.\" man code generated by txt2tags 2.5 (http://txt2tags.sf.net)
.\" cmdline: txt2tags -o- wmiir.man1

