#!/bin/sh
export IXP_ADDRESS="$WMII_ADDRESS"

flags=
while [ "`echo '$1' | head -c 1`" = '-' ]; do
	flags="$flags $1" ; shift
done

if [ -n "$3" ]; then
	com="$1"; file="$2"; shift 2
	echo "$@" | ixpc $flags $com $file
else
	exec ixpc $flags $@
fi

