.TH WMIIR 1 wmii-VERSION
.SH NAME
wmiir \(em wrapper script for ixpc
.SH SYNOPSIS
.B wmiir
.RB [ \-a
.IR address ]
.I action
.I file
.br
.B wmiir
.B \-v
.SH DESCRIPTION
.SS Overview
.B wmiir
is a wrapper script for
.BR ixpc (1)
to conveniently access the filesystem of
.BR wmiiwm (1)
from the command line or from shell
scripts. It can be used to configure
.BR wmii (1).

.SS Options
See the manual page of
.BR ixpc (1) .
.SH ENVIRONMENT
.TP
WMII_ADDRESS
The address of the wmiiwm file server to which wmiir will connect.
.SH EXAMPLES
.TP
.B wmiir ls /
This prints the root directory of the wmii filesystem. For more information
about the contents of this filesystem, see
.BR wmiiwm (1).
.TP
.B echo -n quit | wmiir write /ctl
Write 'quit' to the main control file of the wmii filesystem, effectively
leaving wmii.
.TP
.B echo -n view 2 | wmiir write /ctl
Bring into view all clients tagged '2'. To learn about clients and
tags, see
.BR wmii (1).
.SH SEE ALSO
.BR wmii (1),
.BR ixpc (1),
.BR wmiiwm (1)

http://www.cs.bell-labs.com/sys/man/5/INDEX.html
