#!/bin/sh
export IXP_ADDRESS="$WMII_ADDRESS"

flags=
while [ "`echo '$1' | head -c 1`" = '-' ]; do
	flags="$flags $1" ; shift
done

if [ "$1" = 'echo' ]; then
	file="$2"; shift 2
	echo "$@" | ixpc $flags write $file
else
	exec ixpc $flags $@
fi

