#!/bin/sh
# start wmiiwm and wait for its termination

WMII_CONFPATH="$HOME/.wmii-4:CONFPREFIX/wmii-4" export WMII_CONFPATH
WMII_NS_DIR="/tmp/ns.$USER.${DISPLAY%.0}" export WMII_NS_DIR
IXP_ADDRESS="unix!$WMII_NS_DIR/wmii" export IXP_ADDRESS
mkdir -m 700 "$WMII_NS_DIR" 2>/dev/null

mkdir $HOME/.wmii-4 2>/dev/null && CONFPREFIX/wmii-4/welcome &
exec wmiiwm -a $IXP_ADDRESS -r `PATH="$WMII_CONFPATH:$PATH" which wmiirc`
