ROOT=../../..
include $(ROOT)/mk/hdr.mk
include $(ROOT)/mk/wmii.mk

BINARY = __init__.py \
	 event.py    \
	 fs.py       \
	 menu.py     \
	 monitor.py  \
	 util.py

DIR    = $(GLOBALCONF)/python/pygmi
