ROOT=../..
include $(ROOT)/mk/hdr.mk
include $(ROOT)/mk/wmii.mk

DOCS   = README
EXECS  = wmiirc
TEXT   = wmiirc.py
DIRS   = pygmi \
	 pyxp

DIR    = $(GLOBALCONF)/python
DOCDIR = $(DOC)/alternative_wmiircs/python

include $(ROOT)/mk/dir.mk
