#!/bin/sh
# display a welcome message that contains the wmii tutorial

xmessage -file - <<'EOF'
Welcome to wmii, the non-wimp environment of the WMI Project.

This is a small step by step tutorial, intended to make you a little bit
familiar with wmii.

Note: $MODKEY is the Alt-key by default.

Let's go!

- Start two xterms by pressing $MODKEY-Return twice.
- Switch between the three windows: $MODKEY-j, $MODKEY-k
  If you prefer the mouse, then just move the pointer to the desired window.
- Try the other column modes: $MODKEY-s for stack mode, $MODKEY-m for max mode
  Press $MODKEY-d to return to default mode.
- Create a new column with: $MODKEY-Shift-l
  This moves the client right-wards.
- Tag the selected client with another tag: $MODKEY-Shift-2
  IMPORTANT: before you do the next step, note that you can select the current tag
  	with $MODKEY-1.
- Select the new tag: $MODKEY-2
- Select the floating area: $MODKEY-space
- Open the programs menu: $MODKEY-p
  Type 'xclock' and press Enter.
- Move the xclock window: Press $MODKEY, left-click on the window and, while holding
  the button down, move the cursor around.
- Resize the xclock window: Press $MODKEY, right-click the window and, while holding
  the button down, move the cursor around.
- Open the actions menu: $MODKEY-a
  Rerun wmiirc by selecting 'wmiirc'.
- We'll now have a look at the internal filesystem used by wmii.  Executing
  	wmiir read /
  in the shell of the terminal will list all the files in the root directory.
  Entries beginning with a 'd' are directories.
  If you are curious, you can now dig deeper into the directory trees. For instance,
  	wmiir read /bar/
  will show you the content of the bar.

We hope that these steps gave you an idea of how wmii works.  You can reread
them at any time by pressing $MODKEY-a and selecting 'welcome'.

You should now take a look at the wmii(1) man page.  A FAQ is available on
<http://wmii.suckless.org>.
EOF
