#!/bin/sh
set -ef

ifs="$(echo)"
name=$1
vers=$2
dist=$3
desc="Upstream build"
auth="Kris Maglione <kris@suckless.org>"
date=$(date +'%a, %d %b %Y %T %z')
if git rev-parse --git-dir >/dev/null 2>&1; then
	vers=$(git rev-parse --short HEAD)
	desc=$(git log -1 --format='%s')
	auth=$(git log -1 --format='%aN <%aE>')
	date=$(git log -1 --format='%aD')
fi

cat >debian/changelog.new  <<!
$name ($vers) $dist; urgency=low

  * $desc

 -- $auth  $date

$(cat debian/changelog)
!

mv debian/changelog.new debian/changelog

