#!/bin/sh -f

outfile="$1"; shift

# Derived from Russ Cox's 9l in plan9port.
ofiles=""
args=""
for i
do
	case "$i" in
	*.[ao])
		ofiles="$ofiles $i"
		;;
	*)
		args="$args $i"
		;;
	esac
done

xtmp=/tmp/ld.$$.$USER.out

echo LD ${BASE}$outfile
$LD -o $outfile $ofiles $LDFLAGS $args >$xtmp 2>&1
status=$?

sed 's/.*: In function `[^:]*: *//' $xtmp | egrep . | 
egrep -v 'is almost always misused|is dangerous, better use' 
rm -f $xtmp

exit $status

