#!/bin/sh
# start wmiiwm and wait for its termination

wmiiwm -c || exit 1

OLD_PATH="$PATH" export OLD_PATH
PATH="$HOME/.wmii-4:CONFPREFIX/wmii-4:$PATH" export PATH
WMII_ADDRESS=unix!/tmp/ns.$USER.$DISPLAY/wmii export WMII_ADDRESS

mkdir -m 700 /tmp/ns.$USER.${DISPLAY%.0} 2>/dev/null
wmiiwm -a $WMII_ADDRESS &
wmiiwmpid=$!
mkdir $HOME/.wmii-4 2>/dev/null && welcome &
wmiirc &
wait $wmiiwmpid
