.TH WMII 1 wmii-3
.SH NAME
wmii \- window manager improved 2
.SH SYNOPSIS
.B wmii
.SH DESCRIPTION
.SS Overview
.BR wmii (1)
is a script that launches the
.B wmii
window manager and its various utilities and makes sure that they are
configured for use.
.SS Actions
An action is a shell script in the default setup, but it can actually be
any executable file.  It is executed usually by selecting it from the
actions menu.
You can customize an action by copying it from the global action
directory CONFPREFIX/wmii-3 to $HOME/.wmii-3 and then editing the copy to
fit your needs.  Of course you can also create your own actions there; make
sure that they are executable.
.P
Here is a list of the default actions:
.TP 2
status
periodically print date and load average to the bar
.TP 2
quit
leave the window manager nicely
.TP 2
welcome
display a welcome message that contains the wmii tutorial
.TP 2
wmiirc
configure wmii
.SS Configuration
If you feel the need to change the default configuration, then customize (as
described above) the
.B wmiirc
action.  This action is executed at the end of the
.BR wmii (1)
script and does all the work of setting up the window manager, the key
bindings, the bar labels, etc.
.SH FILES
.TP
/tmp/ns.$USER.$DISPLAY/wmii
The wmii socket file which provides a 9P service.
.TP
CONFPREFIX/wmii-3
Global action directory.
.TP
$HOME/.wmii-3
User-specific action directory.  Actions are first searched here.
.SH ENVIRONMENT
.TP
HOME, USER, DISPLAY
See the section
.B FILES
above.
.P
The following variables are set and exported within
.BR wmii (1)
and thus can be used in actions:
.TP
PATH
.BR wmii (1)
adds the local and global actions directory to the existing PATH.
.TP
WMII_ADDRESS
Socket file of
.BR wmii (1).
Used by
.BR wmiir (1).
.SH SEE ALSO
.BR wmiiwm (1),
.BR wmiimenu (1),
.BR wmiir (1)
