ROOT=../..
include $(ROOT)/mk/hdr.mk
include $(ROOT)/mk/wmii.mk

DOCS   = README  \
	 HISTORY \
	 LICENSE
EXECS  = wmiirc
TEXT   = config.rb \
	 config.yaml

DIR    = $(ETC)/wmii$(CONFVERSION)/ruby
DOCDIR = $(DOC)/alternative_wmiircs/ruby
