char binding_spec[] =
	"Control-j           Accept\n"
	"Control-m           Accept\n"
	"Return              Accept\n"
	"Control-Shift-j     Accept literal\n"
	"Control-Shift-m     Accept literal\n"
	"Shift-Return        Accept literal\n"
	"\n"
	"Escape		    Reject\n"
	"Control-Bracketleft Reject\n"
	"\n"
	"Left                Backward char\n"
	"Control-b           Backward char\n"
	"Right               Forward  char\n"
	"Control-f           Forward  char\n"
	"\n"
	"Mod1-b              Backward word\n"
	"Mod1-f              Forward  word\n"
	"\n"
	"Control-a           Backward line\n"
	"Control-e           Forward  line\n"
	"\n"
	"Control-p           History backward\n"
	"Up                  History backward\n"
	"Control-n           History forward\n"
	"Down                History forward\n"
	"\n"
	"Backspace           Kill char\n"
	"Control-h           Kill char\n"
	"Control-Backspace   Kill word\n"
	"Control-w           Kill word\n"
	"Control-u           Kill line\n"
	"Control-k           Delete line\n"
	"\n"
	"Tab                 Complete next\n"
	"Control-i           Complete next\n"
	"Mod1-l              Complete next\n"
	"\n"
	"Mod1-p	            Paste PRIMARY\n"
	"\n"
	"Shift-Tab           Complete prev\n"
	"Control-Shift-i     Complete prev\n"
	"Mod1-h              Complete prev\n"
	"\n"
	"Prior               Complete prevpage\n"
	"Mod1-k              Complete prevpage\n"
	"Next                Complete nextpage\n"
	"Mod1-j              Complete nextpage\n"
	"Home                Complete first\n"
	"Mod1-g              Complete first\n"
	"End                 Complete last\n"
	"Mod1-Shift-g        Complete last\n"
	"\n"
	;
