.TH WMIIR 1 wmii-4
.SH NAME
wmiir \- window manager improved 2 remote
.SH SYNOPSIS
.B wmiir
.RB [ \-a
.IR address ]
.I action
.I file
.br
.B wmiir
.B \-v
.SH DESCRIPTION
.SS Overview
.B wmiir
is a client to access the filesystem of
.BR wmiiwm (1)
from the command line or from shell
scripts. It can be used to configure
.BR wmii (1).
.SS Options
.TP
.BI \-a " address"
Lets you specify the address to which
.B wmiir
will establish a connection. If this option is not supplied, and the
environment variable WMII_ADDRESS is set,
.B wmiir
will use this value as its address. Currently, the address can only be a
unix socket file or a tcp socket. The syntax for
.I address
is taken (along with many other profound ideas) from the Plan 9 operating
system and has the form
.BR unix!/path/to/socket 
for unix socket files, and
.BR tcp!hostname!port
for tcp sockets.
.TP
.B \-v
Prints version information to stdout, then exits.
.TP
The syntax of the actions is as follows:
.TP
.B write
Writes the supplied data from stdin to
.IR file,
overwriting any previous data.  The data to be written is arbitrary
and only gains meaning (and restrictions) when it is interpreted by
.BR wmiiwm (1).
See
.B EXAMPLES
below.
.TP
.B create
Creates file or directory but does not write any data. If the file exists,
nothing is done.
.TP
.B read
Reads file or directory contents
.TP
.B remove
Removes file or directory tree
.SH ENVIRONMENT
.TP
WMII_ADDRESS
See above.
.SH EXAMPLES
.TP
.B wmiir read /
This prints the root directory of the wmii filesystem. For more information
about the contents of this filesystem, see
.BR wmiiwm (1).
.TP
.B echo -n quit | wmiir write /ctl
Write 'quit' to the main control file of the wmii filesystem, effectively
leaving wmii.
.TP
.B echo -n view 2 | wmiir write /ctl
Bring into view all clients tagged '2'. To learn about clients and
tags, see
.BR wmiiwm (1).
.SH SEE ALSO
.BR wmii (1),
.BR wmiiwm (1)

http://www.cs.bell-labs.com/sys/man/5/INDEX.html
