.TH WMIIMENU 1 wmii-3
.SH NAME
wmiimenu \- window manager improved 2 menu
.SH SYNOPSIS
.B wmiimenu
.RB [ \-v ]
.SH DESCRIPTION
.SS Overview
.B wmiimenu
is a generic, highly customizable, and efficient menu for the X Window System,
originally designed for
.BR wmii (1).
It supports arbitrary, user defined menu contents.
.SS Options
.TP
.B \-v
prints version information to stderr, then exits.
.SS Keys 
.B wmiimenu
is completely keyboard controlled, these are the keys:
.TP 2
Any printable character:
append the character to the text in the input field. This works as a filter:
only items containing this text will be displayed.
.TP 2
Left/Right (C-p/C-n)
select the previous/next item.
.TP 2
Tab (C-i)
copy the selected item to the input field.
.TP 2
Enter (C-j)
confirm selection and quit.
.TP 2
Escape (C-[)
quit without selecting an item.
.TP 2
Backspace (C-h)
remove enough characters from the input field to change its filtering effect.
.TP 2
C-u
remove all characters from the input field.
.SS Customization
.B wmiimenu
is customized by providing it a list of newline-separated items from stdin on startup.
The selected item is printed to stdout.
.SH SEE ALSO
.BR wmii (1),
.BR wmiiwm (1),
.BR wmiir (1)
