.TH WMIIFS 1 wmii-3
.SH NAME
wmiifs \- window manager improved 2 filesystem
.SH SYNOPSIS
.B wmiifs
.B \-s
.I socketfile
.SH DESCRIPTION
.SS Overview
.B wmiifs
is a socket-based fileserver which is used for binding other fileserver
filesystems to a specific namespace. It routes filesystem accesses to
the specific fileserver and behaves to the outside as one master
filesystem.
.SS Options
.TP
.BI \-s " socketfile"
specifies the socketfile that
.B wmiifs
should create.
.TP
.B \-v
prints version information to stderr, then exits.
.SS Customization
.B wmiifs
is customized through manipulating its filesystem namespace.
In the default setup of
.BR wmii (1)
the namespace of
.B wmiifs
can be found in /.
.SH SEE ALSO
.BR wmiibar (1),
.BR wmii (1),
.BR wmiiwm (1),
.BR wmiikeys (1),
.BR wmiimenu (1),
.BR wmiir (1)
