ROOT=../../..
include $(ROOT)/mk/hdr.mk
include $(ROOT)/mk/wmii.mk

BINARY = __init__.py    \
	 asyncclient.py \
	 client.py      \
	 dial.py        \
	 fcall.py       \
	 fields.py      \
	 messages.py    \
	 mux.py         \
	 types.py

DIR    = $(GLOBALCONF)/python/pyxp
